### ISSUE TITLE
TypeError when using rescale

### ISSUE THREAD

**Issue by LambertMark** [mjkvaak/ImageDataAugmentor#1]
When I use rescale in ImageDataAugmentor, I get the following error:

TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'.

Here is a snippet of my code:
```
img_data_gen = ImageDataAugmentor(augment=AUGMENTATIONS, augment_seed=seed,rescale=1./255)
image_generator = img_data_gen.flow_from_directory(img_dir+'\\..', 
			shuffle=True, 
			seed=seed, 
			target_size=(img_height,img_width), 
			class_mode = 'binary',
			batch_size = batch_size)
mask_data_gen = ImageDataAugmentor(augment=AUGMENTATIONS, augment_seed=seed, augment_mode='mask',rescale=1./255)
mask_generator = mask_data_gen.flow_from_directory(mask_dir+'\\..',  
			shuffle=True, 
			seed=seed, 
			target_size=(img_height,img_width), 
			class_mode = 'binary', 
			color_mode = 'gray',
			batch_size = batch_size)

train_generator = zip(image_generator, mask_generator)

autoencoder.fit_generator(
	train_generator,
	steps_per_epoch=nb_train_samples/batch_size,
	validation_data=val_generator,
	validation_steps=nb_val_samples/batch_size,
	epochs=nb_epoch,
	verbose=1,
	callbacks=[history, checkpoint])
```

The full traceback is below:

>   File "C:/Users/mdlambe1/Documents/Python Scripts/My_SegNet_ImageDataAugmentor.py", line 179, in <module>
>     callbacks=[history, checkpoint])
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
>     initial_epoch=initial_epoch)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
>     generator_output = next(output_generator)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\utils\data_utils.py", line 709, in get
>     six.reraise(*sys.exc_info())
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\six.py", line 693, in reraise
>     raise value
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\utils\data_utils.py", line 685, in get
>     inputs = self.queue.get(block=True).get()
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\multiprocessing\pool.py", line 657, in get
>     raise self._value
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\multiprocessing\pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
>     return six.next(_SHARED_SEQUENCES[uid])
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\ImageDataAugmentor\iterator.py", line 105, in __next__
>     return self.next(*args, **kwargs)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\ImageDataAugmentor\iterator.py", line 117, in next
>     return self._get_batches_of_transformed_samples(index_array)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\ImageDataAugmentor\iterator.py", line 233, in _get_batches_of_transformed_samples
>     batch_x = np.array([self.image_data_generator.transform_image(x) for x in batch_x])
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\ImageDataAugmentor\iterator.py", line 233, in <listcomp>
>     batch_x = np.array([self.image_data_generator.transform_image(x) for x in batch_x])
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\ImageDataAugmentor\image_data_augmentor.py", line 564, in transform_image
>     image = self.standardize(image)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\ImageDataAugmentor\image_data_augmentor.py", line 488, in standardize
>     x *= self.rescale
> 
> TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('uint8') with casting rule 'same_kind'

**Comment by mjkvaak** [comment]
Thanks for reporting the bug. I will fix it soon but in the meanwhile I can suggest to either add albumentations.ToFloat() to your set of augmentations or define preprocess_input(x): return x/255., and pass it as the preprocessing function.

**Comment by LambertMark** [comment]
Thanks, that looks like it solved that issue, but now I have a follow-up error:

>  File "C:/Users/mdlambe1/Documents/Python Scripts/My_SegNet_ImageDataAugmentor.py", line 180, in <module>
>     callbacks=[history, checkpoint])
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
>     return func(*args, **kwargs)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
>     initial_epoch=initial_epoch)
> 
>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\engine\training_generator.py", line 210, in fit_generator
>     batch_size = x.shape[0]
> 
> AttributeError: 'tuple' object has no attribute 'shape'

**Comment by mjkvaak** [comment]
Based on the error msg, I think you are trying to define your `batch_size' from variable `x', which doesn't have attribute shape. Try passing another value for batch size?

**Comment by LambertMark** [comment]
No, batch_size is fixed at 16 in my code.  That line is coming from keras' fit_generator.  'x' is the output from ImageDataAugmentor in the fit_generator function of keras.

**Comment by mjkvaak** [comment]
Ok, thanks for clarifying. As a quick test, could you still try to change `class_mode = None`, which it probably should be in a segmentation task.

**Comment by LambertMark** [comment]
with `class_mode = None `, I get another error:

>   File "C:\Users\mdlambe1\AppData\Local\Continuum\anaconda3\envs\python37\lib\site-packages\keras\engine\training_utils.py", line 131, in standardize_input_data
>     'with shape ' + str(data_shape))
> 
> ValueError: Error when checking target: expected activation_decoder_5 to have 4 dimensions, but got array with shape (16, 512, 512)

I'm using a binary mask, but the model expects an extra dimension.  The shape needs to be (16, 512, 512, 1).

**Comment by LambertMark** [comment]
I can fix the shape error with:
`train_generator = zip(image_generator, np.expand_dims(mask_generator, axis = -1))` 

But now everything runs without throwing an error, but I don't get a progress bar and my GPU is idle.  Python is using an increasing amount of memory and is processing something, but with a batch size of 16 it should not take many minutes to process a batch, so something is still not right.

**Comment by mjkvaak** [comment]
Ok, I guess the problem with dimensions is because of reading the image with `color_mode = gray`. You could try switch to `color_mode = None` and define your `preprocess_input` to perform the conversion to shape (512, 512, 1), in your use case something like: 
`def preprocess_input(x):
   x = cv2.cvtColor(x, cv2.COLOR_RGB2GRAY) #convert rgb imgs to grayscale
   x = x[:,:,np.newaxis] # add the missing dimension
   x = x/255. # rescale to [0,1]
   return x
`

**Comment by LambertMark** [comment]
Thanks for the help!  I don't think there is any need to change the color_mode.  This seems to work:
```
def image_preprocessing(x):
   x = x/255. # rescale to [0,1]
   return(x)

def mask_preprocessing(x):
   x = x[:,:,np.newaxis] # expand from (512,512) to (512,512,1)
   x = x/255. # rescale to [0,1]
   return(x)

AUGMENTATIONS = albumentations.Compose([
        albumentations.HorizontalFlip(p=0.5),
	albumentations.VerticalFlip(p=0.5),
	albumentations.Rotate(limit=360, border_mode=cv2.BORDER_CONSTANT,value=[0,0,0],mask_value=0,p=0.9),
	albumentations.RandomCrop(img_height,img_width)
        ])

seed=42
img_data_gen = ImageDataAugmentor(augment=AUGMENTATIONS, augment_seed=seed,preprocess_input = image_preprocessing)
image_generator = img_data_gen.flow_from_directory(img_dir+'\\..', 
				shuffle=True, 
				seed=seed, 
				target_size=(img_height,img_width), 
				class_mode = None,
				batch_size = batch_size)
mask_data_gen = ImageDataAugmentor(augment=AUGMENTATIONS, augment_seed=seed, preprocess_input = mask_preprocessing, augment_mode='mask')
mask_generator = mask_data_gen.flow_from_directory(mask_dir+'\\..',  
				shuffle=True, 
				seed=seed, 
				target_size=(img_height,img_width), 
				class_mode =  None, 
				color_mode = 'gray',
				batch_size = batch_size)
```

**Comment by mjkvaak** [comment]
Glad

**Comment by mjkvaak** [comment]
This should work now. FYI the problem was with numpy casting rule when using the inplace operations (+=, *=, etc). I simply changed these operations to explicit versions and the `TypeError` is now gone.

**Comment by mjkvaak** [comment]
The problem mentioned here with `color_mode = 'gray'` has also been fixed. Earlier the script would return images with shape `(height, width)` format with `color_mode = 'gray'` : now the shape is `(height, width, 1)`
