### ISSUE TITLE
Performance may be suboptimal

### ISSUE THREAD

**Issue by AdityaKane2001** [mjkvaak/ImageDataAugmentor#15]
@mjkvaak 
Great work! This was one of the most useful libraries I've seen in a while. I haven't used it yet, but I'm sure it'll be great.

However, it also makes me wonder whether the performance is up to the mark. You may have observed that Keras `Sequence` objects tend to be slower compared to TensorFlow's native `tf.data.Dataset`. Can you shed some light on the same? 
If there's a non negligible difference, the library should be based off of `tf.data.Dataset`, which guarantees good performance. I'll be really happy to contribute to this in that case.

**Comment by mjkvaak** [comment]
Thank you for the kind words :). I have never used `tf.data.Dataset` myself, so I don't know how the performance would compare. How much work do you think there would be to change the `tf.keras.utils.Sequence` instance(s) in the code into `tf.data.Dataset`? If their are interchangeable, I can do it myself. But of course you can also submit a PR for the case.

**Comment by AdityaKane2001** [comment]
@mjkvaak 
Here's the [link](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) to its docs. They are not interchangeable, because `tf.keras.utils.Sequence` is a generator, whereas `tf.data.Dataset` is not. It has lazy execution and is much more scalable. Please take look at the docs. The docs will explain it to you much better than me 😅

**Comment by mjkvaak** [comment]
I read this [thread](https://github.com/tensorflow/tensorflow/issues/39523) which suggest that there exist no simple transition from `Sequence` to `Data`. Unfortunately, I don't currently have the time (nor energy) to engage in any major refractoring. However, if you feel up to the work, I'm willing to consider merging: or you could of course start own project :). Lastly, I would like to hear it from others also, how much this feature is needed.

**Comment by AdityaKane2001** [comment]
@mjkvaak 
I am interested in doing this. As you said, I'll prefer to do this as a separate repo. But the things is, to achieve good performance and scalable compatibility, it's necessary that the code is made up completely using `tf` constructs, meaning that it should not include albumentations or any other library, as it will not play well with TensorFlow's graphs. That's where I'll need some help.

**Comment by mjkvaak** [comment]
I see, if upgrading to `tf.data` effectively rules out use of `albumentations`, then this should definitely be considered as a different project. Namely, a generic dataloader for tensorflow which supports `albumentions` is the essence of this repo.

**Comment by AdityaKane2001** [comment]
Yes I agree.

**Comment by mjkvaak** [comment]
Great! I will close the issue now. Please add links here to your repo once you get everything up and running, so that people can find an alternative.

**Comment by AdityaKane2001** [comment]
Sure
