### ISSUE TITLE
Make it pip package 

### ISSUE THREAD

**Issue by SlinkoIgor** [mjkvaak/ImageDataAugmentor#2]
Great solution!
Wish I can pip install it instead of cloning into project dir

https://docs.python.org/3/distutils/setupscript.html

**Comment by mjkvaak** [comment]
Good request! It should work now with `$ pip install git+https://github.com/mjkvaak/ImageDataAugmentor`. When using conda envs, be mindful that besides `pip` also `git` need to be installed in your [environment](https://stackoverflow.com/a/50141879/10980510): 

```
$ source activate myenv
$ conda install git pip
$ pip install git+https://github.com/mjkvaak/ImageDataAugmentor
```

Closing this issue now but I'm happy to re-open in case you notice something fishy going on.
