### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Factral** [mjkvaak/ImageDataAugmentor#20]
error when declared

> dg = ImageDataAugmentor(augment=AUGMENTATIONS, 
>                         label_augment_mode="mask", 
>                         preprocess_input=preprocess_input,
>                         preprocess_labels=one_hot_encode_masks, 
>                         seed=SEED
>                        )

AttributeError: 'Compose' object has no attribute 'additional_targets'

this is an error that came up when executing this example https://github.com/mjkvaak/ImageDataAugmentor/blob/master/examples/segmentation-with-flow_from_dataframe.ipynb

**Comment by mjkvaak** [comment]
Thanks for reporting this. I got a different error message that resulted from IDA not supporting newer versions of `albumentations`. Try if 
```sh
pip uninstall ImageDataAugmentor
pip install git+https://github.com/mjkvaak/ImageDataAugmentor
```
would solve your issue.

**Comment by Factral** [comment]
thank u!
